export type RootStackParamList = {
  RegisterScreen:undefined;
  Login:undefined;
    Home: undefined;
    Ukrainian: undefined;
    Filipino: undefined;
    FilipinoGreetings: undefined;
    FilipinoBodyParts: undefined;
    FilipinoNewTopic: undefined;
    FilipinoDailyLesson: undefined;
    FilipinoColours: undefined;
    FilipinoFamily: undefined;
    FilipinoFoodAndDrink: undefined;
    FilipinoWeather: undefined;
    FilipinoGeneralTopics: undefined;
    FilipinoHouseItems: undefined;
    FilipinoSports: undefined;
    FilipinoTransports: undefined;
    FilipinoAnimals: undefined;
    FilipinoLessons: undefined;
    FilipinoAccolades: undefined;
    FilipinoLessonQuiz: undefined;
    FilipinoFlashHome: undefined;
    FilipinoFlashNumbersBasic: undefined;
    FilipinoNumbersIntermediate: undefined;
    FilipinoNumbersExpert:undefined;
    Lesson1: undefined;
    Lesson2: undefined;
    Lesson3: undefined;
    Lesson4: undefined;
    NotFound: undefined;
  };
  